#!/usr/bin/env python3
"""build_pdf.py — Merge approved docs/ content into a single PDF

What it does:
1. Reads only the files listed in PDF_ALLOWLIST (explicit allowlist — no wildcard scanning).
   flows/*-module-data-flow.md files are the only exception: they are added automatically
   because they are created per module during development.
   log-*.md files are intentionally excluded (implementation detail, not suitable for PDF audience).
2. For every .html file in docs/ that has a matching .svg (generated by the diagram scripts),
   embeds the SVG as an image AND adds a clickable link to the original interactive HTML file.
3. Prepends a "How to use this document" page at the start of the PDF.
4. Converts everything to one PDF with a table of contents, page numbers, and working internal links.

PDF section order:
  1. How to Use
  2. Business (why)
  3. Requirements (what)
  4. Architecture (how it is structured)
  5. Specifications (how it is implemented)
  6. Flows (how it runs)
  7. Project Status

Usage:
  python3 docs/script/build_pdf.py [docs_dir] [-o output.pdf] [--lang en|zh]

  --lang en   Section labels and UI text in English (default)
  --lang zh   Section labels and UI text in Traditional Chinese

To add a file to the PDF: add it to PDF_ALLOWLIST below. Do not change the discovery logic.

Requires: pip install markdown weasyprint cairosvg --break-system-packages
"""
import sys, os, re, glob
import markdown
from weasyprint import HTML, CSS
import cairosvg

# Maps diagram key (HTML filename without extension) → the one doc it should be injected into.
# The diagram appears exactly once, in its home document.
# For *-module-data-flow-class diagrams, the target is resolved dynamically in inject_diagrams.
DIAGRAM_TARGETS = {
    # Original two
    "architecture":          "architecture/architecture.md",
    "schema":                "specs/data-model.md",
    # State diagram — lives in data-model.md
    "data-model-state":      "specs/data-model.md",
    # Use case diagram — lives in permissions.md
    "permissions-usecase":   "specs/permissions.md",
    # Activity and sequence — both live in module-flow.md (the template)
    # Individual *-module-flow-activity / *-module-flow-sequence are matched dynamically below
    "module-flow-activity":  "flows/module-flow.md",
    "module-flow-sequence":  "flows/module-flow.md",
    # Component diagrams — live in their respective architecture docs
    "backend-component":     "architecture/backend.md",
    "frontend-component":    "architecture/frontend.md",
    # *-module-data-flow-class → matched dynamically in inject_diagrams
}

# Explicit allowlist — the only files that appear in the PDF, in display order.
# Each entry is (section_key, relative_path_from_docs_dir).
# section_key maps to a translated label via SECTION_LABELS below.
# To add a new permanent deliverable doc, append an entry here.
PDF_ALLOWLIST = [
    # 1. Business — understand why before what
    ("business",       "business/business-process.md"),
    ("business",       "business/business-objects.md"),
    ("business",       "business/business-rules.md"),
    # 2. Requirements — what to build
    ("requirements",   "project-requirements.md"),
    # 3. Architecture — how it is structured
    ("architecture",   "architecture/architecture.md"),
    ("architecture",   "architecture/backend.md"),
    ("architecture",   "architecture/frontend.md"),
    ("architecture",   "architecture/database.md"),
    ("architecture",   "architecture/deployment.md"),
    # 4. Specifications — how it is implemented
    ("specifications", "specs/data-model.md"),
    ("specifications", "specs/api-contract.md"),
    ("specifications", "specs/permissions.md"),
    ("specifications", "specs/logging-spec.md"),
    ("specifications", "specs/research.md"),
    ("specifications", "specs/quickstart.md"),
    # 5. Flows — how it runs (individual *-module-data-flow.md added automatically)
    ("flows",          "modules/module-data-flow.md"),
    # 6. Project Status
    ("project",        "codebase-map.md"),
]

# UI strings for each supported language.
# Add a new language by copying the "en" block with a new key.
STRINGS = {
    "en": {
        "pdf_title":     "Project Documentation",
        "toc_heading":   "Table of Contents",
        "diagram_label": "Diagram",
        "diagram_link":  "Open interactive version — drag, zoom, and click connections in your browser.",
        "how_to_use_heading": "How to Use This Document",
        "how_to_use_body": """This document is the single source of truth for this project.
It is generated automatically from the `docs/` folder and updated whenever a module completes.

**Who should read what:**

| Section | Audience | Purpose |
|---|---|---|
| Business | Everyone | Understand the problem being solved and the business rules |
| Requirements | PM, Tech Lead | What the system must do |
| Architecture | Engineers, Tech Lead | How the system is structured and deployed |
| Specifications | Engineers | Schema, API contracts, permissions, logging |
| Flows | Engineers | Code-level execution flows per module |
| Project Status | Tech Lead | What has been built and how code is organized |

**Diagrams:** Static images are embedded in each section.
Click "Open interactive version" to open the live draggable/zoomable version in your browser.

**To regenerate this PDF:**
```
python3 docs/script/build_pdf.py docs --lang en -o docs/project-documentation-en.pdf
```
""",
        "sections": {
            "requirements":   "Requirements",
            "specifications": "Specifications",
            "architecture":   "Architecture",
            "business":       "Business",
            "flows":          "Flows",
            "project":        "Project Status",
        },
    },
    "zh": {
        "pdf_title":     "專案文件",
        "toc_heading":   "目錄",
        "diagram_label": "圖表",
        "diagram_link":  "開啟互動版本 — 可在瀏覽器中拖曳、縮放並點擊連線。",
        "how_to_use_heading": "如何使用本文件",
        "how_to_use_body": """本文件是專案的唯一事實來源，從 `docs/` 資料夾自動生成，每次模組完成時更新。

**各區塊的目標讀者：**

| 區塊 | 讀者 | 用途 |
|---|---|---|
| Business | 所有人 | 理解系統解決的業務問題與業務規則 |
| Requirements | PM、技術負責人 | 系統必須做什麼 |
| Architecture | 工程師、技術負責人 | 系統如何組成與部署 |
| Specifications | 工程師 | Schema、API 合約、權限、日誌規則 |
| Flows | 工程師 | 各模組的程式碼層級執行流程 |
| Project Status | 技術負責人 | 已完成的內容與程式碼組織方式 |

**圖表：** 靜態圖片已嵌入各區塊，點擊「開啟互動版本」可在瀏覽器中查看可拖曳/縮放的版本。

**重新生成 PDF：**
```
python3 docs/script/build_pdf.py docs-zh --lang zh -o docs/project-documentation-zh.pdf
```
""",
        "sections": {
            "requirements":   "需求",
            "specifications": "規格",
            "architecture":   "架構",
            "business":       "業務",
            "flows":          "流程",
            "project":        "專案狀態",
        },
    },
}

CSS_FONT_EN = "'Segoe UI', Arial, sans-serif"
CSS_FONT_ZH = "'Noto Sans CJK TC', 'Noto Sans TC', 'Microsoft JhengHei', 'Segoe UI', Arial, sans-serif"


def find_allowed_files(docs_dir, strings):
    """Return (rel, abs_path, section_label) for every allowlisted file that exists.
    Also auto-includes any flows/*-flow.md files (individual module flow files created
    during development). log-*.md files are intentionally excluded — they contain
    low-level implementation details not suitable for the PDF audience."""
    result = []
    seen = set()

    for section_key, rel in PDF_ALLOWLIST:
        abs_path = os.path.join(docs_dir, rel)
        section_label = strings["sections"][section_key]
        if os.path.exists(abs_path):
            result.append((rel, abs_path, section_label))
            seen.add(rel)
        else:
            print(f"Warning: allowlisted file not found, skipping: {rel}")

    flows_label = strings["sections"]["flows"]
    for path in sorted(glob.glob(os.path.join(docs_dir, "modules", "*", "*-module-data-flow.md"))):
        rel = os.path.relpath(path, docs_dir)
        if rel not in seen:
            # Insert before codebase-map (last entry) so flow files sit under Flows
            result.insert(-1, (rel, path, flows_label))

    return result


def find_html_svg_pairs(docs_dir):
    """Find .html files that have a matching .svg (from architecture_to_html.py / schema_to_html.py)."""
    pairs = {}
    for html_path in glob.glob(os.path.join(docs_dir, "**", "*.html"), recursive=True):
        svg_path = os.path.splitext(html_path)[0] + ".svg"
        if os.path.exists(svg_path):
            key = os.path.splitext(os.path.basename(html_path))[0]
            pairs[key] = {"html": html_path, "svg": svg_path}
    return pairs


def svg_to_png(svg_path, out_path, width=1400):
    cairosvg.svg2png(url=svg_path, write_to=out_path, output_width=width)
    return out_path


def inject_diagrams(md_text, rel, docs_dir, html_svg_pairs, png_cache_dir, strings):
    """Inject a rendered PNG + clickable link for diagrams whose target doc matches rel.

    Fixed targets come from DIAGRAM_TARGETS.
    Dynamic targets: a key ending in '-module-data-flow-class' maps to the
    corresponding '[module]-module-data-flow.md' file in flows/.
    """
    for key, pair in html_svg_pairs.items():
        # Resolve target: fixed mapping first, then dynamic module-data-flow-class pattern
        target = DIAGRAM_TARGETS.get(key)
        if target is None:
            # Dynamic: order-module-data-flow-class → modules/order/order-module-data-flow.md
            m = re.match(r'^(.+)-class$', key)
            if m:
                base = m.group(1)  # e.g. order-module-data-flow
                # Extract module name: order-module-data-flow -> order
                module_name = base.replace('-module-data-flow', '')
                target = f"modules/{module_name}/{base}.md"

        if target != rel:
            continue

        png_name = f"{key}.png"
        png_path = os.path.join(png_cache_dir, png_name)
        if not os.path.exists(png_path):
            svg_to_png(pair["svg"], png_path)

        png_rel = os.path.relpath(png_path, docs_dir)
        html_rel = os.path.relpath(pair["html"], docs_dir)
        block = (
            f"\n\n> **{strings['diagram_label']}: {key}**\n"
            f">\n"
            f"> ![{key} diagram]({png_rel})\n"
            f">\n"
            f"> 🔗 [{strings['diagram_link']}]({html_rel})\n\n"
        )
        md_text += block

    return md_text


def build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings):
    files = find_allowed_files(docs_dir, strings)
    if not files:
        print("No files to include — check PDF_ALLOWLIST in build_pdf.py")
        sys.exit(1)

    parts = [f"# {strings['pdf_title']}\n"]

    # How to use page
    parts.append(f"\n\n# {strings['how_to_use_heading']}\n\n{strings['how_to_use_body']}\n")

    parts.append(f"## {strings['toc_heading']}\n")
    toc_lines = []
    body_parts = []

    current_section = None
    for rel, abs_path, section_label in files:
        if section_label != current_section:
            body_parts.append(f"\n\n# {section_label}\n")
            toc_lines.append(f"- **{section_label}**")
            current_section = section_label

        with open(abs_path, "r", encoding="utf-8") as f:
            content = f.read()

        content = inject_diagrams(content, rel, docs_dir, html_svg_pairs, png_cache_dir, strings)

        # Use the first # H1 heading from the file as the title; fall back to filename.
        h1_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        title = h1_match.group(1).strip() if h1_match else os.path.splitext(os.path.basename(rel))[0]
        # Strip the leading H1 from the file content — the section wrapper below already provides it.
        content_body = re.sub(r"^#\s+.+\n?", "", content, count=1)
        toc_lines.append(f"  - {title}")
        body_parts.append(f"\n\n## {title}\n\n{content_body}")

    parts.append("\n".join(toc_lines))
    parts.extend(body_parts)
    return "\n".join(parts)


def build_css(lang):
    font = CSS_FONT_ZH if lang == "zh" else CSS_FONT_EN
    return f"""
@page {{
    size: A4;
    margin: 2cm;
    @bottom-center {{
        content: counter(page) " / " counter(pages);
        font-size: 9px;
        color: #888;
    }}
}}
body {{
    font-family: {font};
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1a1a1a;
}}
h1 {{
    font-size: 20pt;
    border-bottom: 2px solid #2D3748;
    padding-bottom: 6px;
    page-break-before: always;
}}
h1:first-of-type {{ page-break-before: avoid; }}
h2 {{
    font-size: 14pt;
    color: #2D3748;
    margin-top: 24px;
    border-bottom: 1px solid #ddd;
    padding-bottom: 4px;
}}
h3 {{ font-size: 12pt; color: #2B6CB0; }}
code {{
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 9pt;
}}
pre {{
    background: #1A202C;
    color: #E2E8F0;
    padding: 10px;
    border-radius: 6px;
    font-size: 8.5pt;
    overflow-x: auto;
    white-space: pre-wrap;
}}
pre code {{ background: none; color: inherit; padding: 0; }}
table {{
    border-collapse: collapse;
    width: 100%;
    font-size: 9pt;
    margin: 12px 0;
}}
th, td {{
    border: 1px solid #ccc;
    padding: 4px 8px;
    text-align: left;
}}
th {{ background: #2D3748; color: white; }}
blockquote {{
    border-left: 4px solid #3182CE;
    margin: 12px 0;
    padding: 8px 16px;
    background: #EBF8FF;
}}
img {{ max-width: 100%; }}
a {{ color: #3182CE; text-decoration: none; }}
"""


def parse_args():
    args = sys.argv[1:]
    docs_dir = "docs"
    output_path = None
    lang = "en"

    i = 0
    while i < len(args):
        a = args[i]
        if a == "-o" and i + 1 < len(args):
            output_path = args[i + 1]
            i += 2
        elif a == "--lang" and i + 1 < len(args):
            lang = args[i + 1]
            i += 2
        elif not a.startswith("-"):
            docs_dir = a
            i += 1
        else:
            i += 1

    if lang not in STRINGS:
        print(f"Unsupported language '{lang}'. Available: {', '.join(STRINGS)}")
        sys.exit(1)

    if not output_path:
        output_path = f"project-documentation-{lang}.pdf"

    return docs_dir, output_path, lang


def main():
    docs_dir, output_path, lang = parse_args()
    strings = STRINGS[lang]

    if not os.path.isdir(docs_dir):
        print(f"Directory not found: {docs_dir}")
        sys.exit(1)

    png_cache_dir = os.path.join(docs_dir, ".pdf_build_cache")
    os.makedirs(png_cache_dir, exist_ok=True)

    html_svg_pairs = find_html_svg_pairs(docs_dir)
    print(f"Found {len(html_svg_pairs)} diagram(s): {list(html_svg_pairs.keys())}")
    print(f"Language: {lang}")

    merged_md = build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings)

    md_html = markdown.markdown(
        merged_md,
        extensions=["tables", "fenced_code", "toc", "nl2br"]
    )

    full_html = f"<html><head><meta charset='utf-8'></head><body>{md_html}</body></html>"

    HTML(string=full_html, base_url=docs_dir).write_pdf(
        output_path,
        stylesheets=[CSS(string=build_css(lang))]
    )

    print(f"Done: {output_path}")


if __name__ == "__main__":
    main()
