#!/usr/bin/env python3
"""build_pdf.py — Merge approved docs/ content into a single PDF

What it does:
1. Reads only the files listed in PDF_ALLOWLIST (explicit allowlist — no wildcard scanning).
   flows/log-*.md files are the only exception: they are added automatically because the
   Module Completion Check in AGENTS.md creates one per module as modules finish.
2. For every .html file in docs/ that has a matching .svg (generated by architecture_to_html.py /
   schema_to_html.py), embeds the SVG as an image AND adds a clickable link to the original
   interactive HTML file (opens in browser when double-clicked from the PDF, on most readers)
3. Converts everything to one PDF with a table of contents, page numbers, and working internal links

Usage:
  python3 docs/script/build_pdf.py [docs_dir] [-o output.pdf] [--lang en|zh]

  --lang en   Section labels and UI text in English (default)
  --lang zh   Section labels and UI text in Traditional Chinese

To add a file to the PDF: add it to PDF_ALLOWLIST below. Do not change the discovery logic.

Requires: pip install markdown weasyprint cairosvg --break-system-packages
"""
import sys, os, re, glob
import markdown
from weasyprint import HTML, CSS
import cairosvg

# Maps diagram key (HTML filename without extension) → the one doc it should be injected into.
# The diagram appears exactly once, in its home document.
DIAGRAM_TARGETS = {
    "architecture": "architecture/architecture.md",
    "schema":       "specs/data-model.md",
}

# Explicit allowlist — the only files that appear in the PDF, in display order.
# Each entry is (section_key, relative_path_from_docs_dir).
# section_key maps to a translated label via SECTION_LABELS below.
# To add a new permanent deliverable doc, append an entry here.
PDF_ALLOWLIST = [
    ("requirements",   "project-requirements.md"),
    ("specifications", "specs/research.md"),
    ("specifications", "specs/quickstart.md"),
    ("specifications", "specs/data-model.md"),
    ("specifications", "specs/api-contract.md"),
    ("specifications", "specs/permissions.md"),
    ("architecture",   "architecture/architecture.md"),
    ("architecture",   "architecture/backend.md"),
    ("architecture",   "architecture/frontend.md"),
    ("architecture",   "architecture/database.md"),
    ("architecture",   "architecture/deployment.md"),
    ("business",       "business/business-rules.md"),
    ("business",       "business/business-objects.md"),
    ("business",       "business/business-process.md"),
    ("flows",          "flows/module-data-flow.md"),
    # flows/log-*.md entries are added automatically below (Module Completion Check output)
    ("project",        "codebase-map.md"),
]

# UI strings for each supported language.
# Add a new language by copying the "en" block with a new key.
STRINGS = {
    "en": {
        "pdf_title":     "Project Documentation",
        "toc_heading":   "Table of Contents",
        "diagram_label": "Diagram",
        "diagram_link":  "Open interactive version — drag, zoom, and click connections in your browser.",
        "sections": {
            "requirements":   "Requirements",
            "specifications": "Specifications",
            "architecture":   "Architecture",
            "business":       "Business",
            "flows":          "Flows",
            "project":        "Project",
        },
    },
    "zh": {
        "pdf_title":     "專案文件",
        "toc_heading":   "目錄",
        "diagram_label": "圖表",
        "diagram_link":  "開啟互動版本 — 可在瀏覽器中拖曳、縮放並點擊連線。",
        "sections": {
            "requirements":   "需求",
            "specifications": "規格",
            "architecture":   "架構",
            "business":       "業務",
            "flows":          "流程",
            "project":        "專案",
        },
    },
}

CSS_FONT_EN = "'Segoe UI', Arial, sans-serif"
CSS_FONT_ZH = "'Noto Sans CJK TC', 'Noto Sans TC', 'Microsoft JhengHei', 'Segoe UI', Arial, sans-serif"


def find_allowed_files(docs_dir, strings):
    """Return (rel, abs_path, section_label) for every allowlisted file that exists.
    Also appends any flows/log-*.md files found on disk (created by Module Completion Check)."""
    result = []
    seen = set()

    for section_key, rel in PDF_ALLOWLIST:
        abs_path = os.path.join(docs_dir, rel)
        section_label = strings["sections"][section_key]
        if os.path.exists(abs_path):
            result.append((rel, abs_path, section_label))
            seen.add(rel)
        else:
            print(f"Warning: allowlisted file not found, skipping: {rel}")

    flows_label = strings["sections"]["flows"]
    for path in sorted(glob.glob(os.path.join(docs_dir, "flows", "log-*.md"))):
        rel = os.path.relpath(path, docs_dir)
        if rel not in seen:
            # Insert before codebase-map (last entry) so log files sit under Flows
            result.insert(-1, (rel, path, flows_label))

    return result


def find_html_svg_pairs(docs_dir):
    """Find .html files that have a matching .svg (from architecture_to_html.py / schema_to_html.py)."""
    pairs = {}
    for html_path in glob.glob(os.path.join(docs_dir, "**", "*.html"), recursive=True):
        svg_path = os.path.splitext(html_path)[0] + ".svg"
        if os.path.exists(svg_path):
            key = os.path.splitext(os.path.basename(html_path))[0]
            pairs[key] = {"html": html_path, "svg": svg_path}
    return pairs


def svg_to_png(svg_path, out_path, width=1400):
    cairosvg.svg2png(url=svg_path, write_to=out_path, output_width=width)
    return out_path


def inject_diagrams(md_text, rel, docs_dir, html_svg_pairs, png_cache_dir, strings):
    """Inject a rendered PNG + clickable link for diagrams whose target doc matches rel."""
    for key, pair in html_svg_pairs.items():
        target = DIAGRAM_TARGETS.get(key)
        if target != rel:
            continue

        png_name = f"{key}.png"
        png_path = os.path.join(png_cache_dir, png_name)
        if not os.path.exists(png_path):
            svg_to_png(pair["svg"], png_path)

        png_rel = os.path.relpath(png_path, docs_dir)
        html_rel = os.path.relpath(pair["html"], docs_dir)
        block = (
            f"\n\n> **{strings['diagram_label']}: {key}**\n"
            f">\n"
            f"> ![{key} diagram]({png_rel})\n"
            f">\n"
            f"> 🔗 [{strings['diagram_link']}]({html_rel})\n\n"
        )
        md_text += block

    return md_text


def build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings):
    files = find_allowed_files(docs_dir, strings)
    if not files:
        print("No files to include — check PDF_ALLOWLIST in build_pdf.py")
        sys.exit(1)

    parts = [f"# {strings['pdf_title']}\n"]
    parts.append(f"## {strings['toc_heading']}\n")
    toc_lines = []
    body_parts = []

    current_section = None
    for rel, abs_path, section_label in files:
        if section_label != current_section:
            body_parts.append(f"\n\n# {section_label}\n")
            toc_lines.append(f"- **{section_label}**")
            current_section = section_label

        with open(abs_path, "r", encoding="utf-8") as f:
            content = f.read()

        content = inject_diagrams(content, rel, docs_dir, html_svg_pairs, png_cache_dir, strings)

        # Use the first # H1 heading from the file as the title; fall back to filename.
        h1_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        title = h1_match.group(1).strip() if h1_match else os.path.splitext(os.path.basename(rel))[0]
        # Strip the leading H1 from the file content — the section wrapper below already provides it.
        content_body = re.sub(r"^#\s+.+\n?", "", content, count=1)
        toc_lines.append(f"  - {title}")
        body_parts.append(f"\n\n## {title}\n\n{content_body}")

    parts.append("\n".join(toc_lines))
    parts.extend(body_parts)
    return "\n".join(parts)


def build_css(lang):
    font = CSS_FONT_ZH if lang == "zh" else CSS_FONT_EN
    return f"""
@page {{
    size: A4;
    margin: 2cm;
    @bottom-center {{
        content: counter(page) " / " counter(pages);
        font-size: 9px;
        color: #888;
    }}
}}
body {{
    font-family: {font};
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1a1a1a;
}}
h1 {{
    font-size: 20pt;
    border-bottom: 2px solid #2D3748;
    padding-bottom: 6px;
    page-break-before: always;
}}
h1:first-of-type {{ page-break-before: avoid; }}
h2 {{
    font-size: 14pt;
    color: #2D3748;
    margin-top: 24px;
    border-bottom: 1px solid #ddd;
    padding-bottom: 4px;
}}
h3 {{ font-size: 12pt; color: #2B6CB0; }}
code {{
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 9pt;
}}
pre {{
    background: #1A202C;
    color: #E2E8F0;
    padding: 10px;
    border-radius: 6px;
    font-size: 8.5pt;
    overflow-x: auto;
    white-space: pre-wrap;
}}
pre code {{ background: none; color: inherit; padding: 0; }}
table {{
    border-collapse: collapse;
    width: 100%;
    font-size: 9pt;
    margin: 12px 0;
}}
th, td {{
    border: 1px solid #ccc;
    padding: 4px 8px;
    text-align: left;
}}
th {{ background: #2D3748; color: white; }}
blockquote {{
    border-left: 4px solid #3182CE;
    margin: 12px 0;
    padding: 8px 16px;
    background: #EBF8FF;
}}
img {{ max-width: 100%; }}
a {{ color: #3182CE; text-decoration: none; }}
"""


def parse_args():
    args = sys.argv[1:]
    docs_dir = "docs"
    output_path = None
    lang = "en"

    i = 0
    while i < len(args):
        a = args[i]
        if a == "-o" and i + 1 < len(args):
            output_path = args[i + 1]
            i += 2
        elif a == "--lang" and i + 1 < len(args):
            lang = args[i + 1]
            i += 2
        elif not a.startswith("-"):
            docs_dir = a
            i += 1
        else:
            i += 1

    if lang not in STRINGS:
        print(f"Unsupported language '{lang}'. Available: {', '.join(STRINGS)}")
        sys.exit(1)

    if not output_path:
        output_path = f"project-documentation-{lang}.pdf"

    return docs_dir, output_path, lang


def main():
    docs_dir, output_path, lang = parse_args()
    strings = STRINGS[lang]

    if not os.path.isdir(docs_dir):
        print(f"Directory not found: {docs_dir}")
        sys.exit(1)

    png_cache_dir = os.path.join(docs_dir, ".pdf_build_cache")
    os.makedirs(png_cache_dir, exist_ok=True)

    html_svg_pairs = find_html_svg_pairs(docs_dir)
    print(f"Found {len(html_svg_pairs)} diagram(s): {list(html_svg_pairs.keys())}")
    print(f"Language: {lang}")

    merged_md = build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings)

    md_html = markdown.markdown(
        merged_md,
        extensions=["tables", "fenced_code", "toc", "nl2br"]
    )

    full_html = f"<html><head><meta charset='utf-8'></head><body>{md_html}</body></html>"

    HTML(string=full_html, base_url=docs_dir).write_pdf(
        output_path,
        stylesheets=[CSS(string=build_css(lang))]
    )

    print(f"Done: {output_path}")


if __name__ == "__main__":
    main()
