#!/usr/bin/env python3
"""build_pdf.py — Merge all docs/ content into a single PDF

What it does:
1. Walks docs/ (skips docs/templates/ if present — that's the blank-template area, not real content)
2. Reads every .md file, in a sensible order (specs -> architecture -> business -> flows -> root)
3. For every .html file in docs/ that has a matching .svg (generated by architecture_to_html.py /
   schema_to_html.py), embeds the SVG as an image AND adds a clickable link to the original
   interactive HTML file (opens in browser when double-clicked from the PDF, on most readers)
4. Converts everything to one PDF with a table of contents, page numbers, and working internal links

Usage:
  python3 docs/script/build_pdf.py [docs_dir] [-o output.pdf]

Requires: pip install markdown weasyprint cairosvg --break-system-packages
"""
import sys, os, re, glob
import markdown
from weasyprint import HTML, CSS
import cairosvg

# Order in which top-level docs/ sections appear in the merged PDF.
# Anything not matching these prefixes falls into "Other" at the end.
SECTION_ORDER = [
    ("specs", "Specifications"),
    ("architecture", "Architecture"),
    ("business", "Business"),
    ("flows", "Flows"),
]

SKIP_DIRS = {"templates", "script", "plans", "refactor", "rules"}  # internal planning/process docs — excluded from PDF


def find_markdown_files(docs_dir):
    """Return (relative_path, absolute_path) pairs, root-level files first, then by SECTION_ORDER."""
    root_files = []
    sectioned = {key: [] for key, _ in SECTION_ORDER}
    other_files = []

    for path in sorted(glob.glob(os.path.join(docs_dir, "**", "*.md"), recursive=True)):
        rel = os.path.relpath(path, docs_dir)
        top = rel.split(os.sep)[0]

        if top in SKIP_DIRS:
            continue

        if os.sep not in rel:
            root_files.append((rel, path))
        else:
            matched = False
            for key, _ in SECTION_ORDER:
                if top == key:
                    sectioned[key].append((rel, path))
                    matched = True
                    break
            if not matched:
                other_files.append((rel, path))

    ordered = []
    for key, _ in SECTION_ORDER:
        ordered.extend(sorted(sectioned[key]))
    ordered.extend(sorted(other_files))
    # root-level docs (current-state, changelog, codebase-map) go last — they're logs, not specs
    ordered.extend(sorted(root_files))
    return ordered


def find_html_svg_pairs(docs_dir):
    """Find .html files that have a matching .svg (from architecture_to_html.py / schema_to_html.py)."""
    pairs = {}
    for html_path in glob.glob(os.path.join(docs_dir, "**", "*.html"), recursive=True):
        svg_path = os.path.splitext(html_path)[0] + ".svg"
        if os.path.exists(svg_path):
            key = os.path.splitext(os.path.basename(html_path))[0]
            pairs[key] = {"html": html_path, "svg": svg_path}
    return pairs


def svg_to_png(svg_path, out_path, width=1400):
    cairosvg.svg2png(url=svg_path, write_to=out_path, output_width=width)
    return out_path


def inject_diagrams(md_text, docs_dir, html_svg_pairs, png_cache_dir):
    """
    If the markdown text mentions a diagram (e.g. references architecture.html, or has a
    'Structured Definition' YAML block matching a known diagram), inject the rendered PNG +
    a clickable link to the original interactive HTML right after that section.

    All injected paths are relative to docs_dir, since that is what HTML(base_url=...) uses.
    """
    for key, pair in html_svg_pairs.items():
        pattern = re.compile(re.escape(key), re.IGNORECASE)
        if not pattern.search(md_text):
            continue

        png_name = f"{key}.png"
        png_path = os.path.join(png_cache_dir, png_name)
        if not os.path.exists(png_path):
            svg_to_png(pair["svg"], png_path)

        png_rel = os.path.relpath(png_path, docs_dir)
        html_rel = os.path.relpath(pair["html"], docs_dir)
        block = (
            f"\n\n> **Diagram: {key}**\n"
            f">\n"
            f"> ![{key} diagram]({png_rel})\n"
            f">\n"
            f"> 🔗 [Open interactive version]({html_rel}) "
            f"— drag, zoom, and click connections in your browser.\n\n"
        )
        # Append once after the first mention's paragraph, or just at the end if unsure.
        md_text += block

    return md_text


def build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir):
    files = find_markdown_files(docs_dir)
    if not files:
        print(f"No markdown files found under {docs_dir} (excluding templates/, script/)")
        sys.exit(1)

    parts = ["# Project Documentation\n"]
    parts.append("## Table of Contents\n")
    toc_lines = []
    body_parts = []

    current_section = None
    for rel, abs_path in files:
        top = rel.split(os.sep)[0] if os.sep in rel else "Root"
        section_label = dict(SECTION_ORDER).get(top, "Other" if os.sep in rel else "Project Status")

        if section_label != current_section:
            body_parts.append(f"\n\n# {section_label}\n")
            toc_lines.append(f"- **{section_label}**")
            current_section = section_label

        with open(abs_path, "r", encoding="utf-8") as f:
            content = f.read()

        content = inject_diagrams(content, docs_dir, html_svg_pairs, png_cache_dir)

        # Use the first # H1 heading from the file as the title; fall back to filename.
        h1_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        title = h1_match.group(1).strip() if h1_match else os.path.splitext(os.path.basename(rel))[0]
        toc_lines.append(f"  - {title} (`{rel}`)")
        body_parts.append(f"\n\n## {title}\n*`{rel}`*\n\n{content}")

    parts.append("\n".join(toc_lines))
    parts.extend(body_parts)
    return "\n".join(parts)


PDF_CSS = """
@page {
    size: A4;
    margin: 2cm;
    @bottom-center {
        content: counter(page) " / " counter(pages);
        font-size: 9px;
        color: #888;
    }
}
body {
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.5;
    color: #1a1a1a;
}
h1 {
    font-size: 20pt;
    border-bottom: 2px solid #2D3748;
    padding-bottom: 6px;
    page-break-before: always;
}
h1:first-of-type { page-break-before: avoid; }
h2 {
    font-size: 14pt;
    color: #2D3748;
    margin-top: 24px;
    border-bottom: 1px solid #ddd;
    padding-bottom: 4px;
}
h3 { font-size: 12pt; color: #2B6CB0; }
code {
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 9pt;
}
pre {
    background: #1A202C;
    color: #E2E8F0;
    padding: 10px;
    border-radius: 6px;
    font-size: 8.5pt;
    overflow-x: auto;
    white-space: pre-wrap;
}
pre code { background: none; color: inherit; padding: 0; }
table {
    border-collapse: collapse;
    width: 100%;
    font-size: 9pt;
    margin: 12px 0;
}
th, td {
    border: 1px solid #ccc;
    padding: 4px 8px;
    text-align: left;
}
th { background: #2D3748; color: white; }
blockquote {
    border-left: 4px solid #3182CE;
    margin: 12px 0;
    padding: 8px 16px;
    background: #EBF8FF;
}
img { max-width: 100%; }
a { color: #3182CE; text-decoration: none; }
"""


def main():
    docs_dir = sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("-") else "docs"
    output_path = None
    if "-o" in sys.argv:
        output_path = sys.argv[sys.argv.index("-o") + 1]
    if not output_path:
        output_path = "project-documentation.pdf"

    if not os.path.isdir(docs_dir):
        print(f"Directory not found: {docs_dir}")
        sys.exit(1)

    png_cache_dir = os.path.join(docs_dir, ".pdf_build_cache")
    os.makedirs(png_cache_dir, exist_ok=True)

    html_svg_pairs = find_html_svg_pairs(docs_dir)
    print(f"Found {len(html_svg_pairs)} diagram(s) with HTML+SVG pairs: {list(html_svg_pairs.keys())}")

    merged_md = build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir)

    md_html = markdown.markdown(
        merged_md,
        extensions=["tables", "fenced_code", "toc", "nl2br"]
    )

    full_html = f"<html><head><meta charset='utf-8'></head><body>{md_html}</body></html>"

    HTML(string=full_html, base_url=docs_dir).write_pdf(
        output_path,
        stylesheets=[CSS(string=PDF_CSS)]
    )

    print(f"Done: {output_path}")


if __name__ == "__main__":
    main()
